//Authentication and authorization
export const USER = 'USER';

//NAV_BAR
export const NAV_BAR_ADMIN = 'NAV_BAR_ADMIN';
export const NAV_BAR_BUSINESS = 'NAV_BAR_BUSINESS';
export const NAV_BAR_USER = 'NAV_BAR_USER';
export const NAV_BAR_COUNTDOWN = 'NAV_BAR_COUNTDOWN';


//Admins
export const ADMIN_APPROVE_PRODUCTS = 'ADMIN_APPROVE_PRODUCTS';
export const ADMIN_APPROVE_PRODUCT_REMOVE = 'ADMIN_APPROVE_PRODUCT_REMOVE';
export const ADMIN_APPROVE_BUSINESSES = 'ADMIN_APPROVE_BUSINESSES';
export const ADMIN_APPROVE_BUSINESS_REMOVE = 'ADMIN_APPROVE_BUSINESS_REMOVE';
export const ADMIN_APPROVE = 'ADMIN_APPROVE';


//MENUS
export const MENU_DISPLAY = 'MENU_DISPLAY';
export const MENU_REMOVE = 'MENU_REMOVE';


//BUSINESS
export const BUSINESS = 'BUSINESS';
export const REMOVE_BUSINESS = 'REMOVE_BUSINESS';
export const BUSINESS_INFO = 'BUSINESS_INFO';


//SERVER URL
export const URL = 'URL';

//ERRORS
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

//SUCCESS
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const REMOVE_SUCCESS = 'REMOVE_SUCCESS';

//WARNINGS
export const REMOVE_WARNING = 'REMOVE_WARNING';
export const ADD_WARNING = 'ADD_WARNING';

//AUTH
export const AUTH = 'AUTH';

//Projects
export const PROJECTS = 'PROJECTS';


